Repository openshift/sandboxed-containers-operator, pull requests merged in 2021-04, with the labels that each got.

#81 controller: The CRI-O drop-in file should be provided by the RPM
  controllers/openshift_controller.go
Labels: needs-rebase

#89 machine-config needs a name
  controllers/openshift_controller.go
Labels: lgtm

#93 use completedNodesCount field
  controllers/openshift_controller.go
Labels: backport-needed

#90 [backport] inform user if kata uninstallation is blocked by existing kata-based …
  api/v1/kataconfig_types.go
  config/crd/bases/kataconfiguration.openshift.io_kataconfigs.yaml
  controllers/openshift_controller.go
Labels: backport-needed, lgtm

#91 [backport] controller: The service should ne enabled by the OS
  controllers/openshift_controller.go
Labels: backport-needed, lgtm

#94 controller: The CRI-O drop-in file should be provided by the RPM
  controllers/openshift_controller.go
Labels: lgtm
