Repository openshift/sandboxed-containers-operator, pull requests merged in 2023-04, with the labels that each got.

#282 controller: use new naming peerpodconfig-ctrl
  PROJECT
  controllers/openshift_controller.go
  go.mod
  go.sum
  main.go
Labels: lgtm

#274 Optionally use public images
  Dockerfile
  Makefile
  docs/DEVELOPMENT.md
Labels: lgtm, ok-to-test

#289 controller: automatically create a Secret containing the cluster's pull-secret
  controllers/openshift_controller.go
Labels: ok-to-test

#302 Merge main into peer-pods-tech-preview
  Dockerfile
  Makefile
  api/v1/kataconfig_types.go
  controllers/openshift_controller.go
  docs/DEVELOPMENT.md
Labels: lgtm
