Repository openshift/sandboxed-containers-operator, pull requests merged in 2024-08, with the labels that each got.

#433 Sandboxed containers operator to build secure execution enabled peer pod Image
  config/peerpods/peerpodssecret.yaml
  config/peerpods/podvm/lib.sh
  config/peerpods/podvm/libvirt-podvm-image-cm.yaml
  config/peerpods/podvm/libvirt-podvm-image-handler.sh
Labels: needs-ok-to-test, lgtm

#442 1.7 release: bump peerpod controllers to 0.9.0
  PROJECT
  controllers/openshift_controller.go
  go.mod
  go.sum
  main.go
Labels: lgtm

#446 Sync release-1.7 with devel
  PROJECT
  config/peerpods/credentials-requests/credentials_request_aws.yaml
  config/peerpods/credentials-requests/credentials_request_azure.yaml
  config/peerpods/peerpodssecret.yaml
  config/peerpods/podvm/lib.sh
  config/peerpods/podvm/libvirt-podvm-image-cm.yaml
  config/peerpods/podvm/libvirt-podvm-image-handler.sh
  config/peerpods/podvm/osc-podvm-create-job.yaml
  config/peerpods/podvm/osc-podvm-delete-job.yaml
  controllers/openshift_controller.go
  go.mod
  go.sum
  main.go
Labels: lgtm

#431 KATA-2987: Enable OCI image pull support for libvirt provider
  config/peerpods/podvm/Dockerfile.podvm-oci
  config/peerpods/podvm/README.md
  config/peerpods/podvm/lib.sh
  config/peerpods/podvm/libvirt-podvm-image-cm.yaml
  config/peerpods/podvm/libvirt-podvm-image-handler.sh
  config/peerpods/podvm/podvm-builder.sh
  config/peerpods/podvm/podvm-handling.md
Labels: lgtm, jira/valid-reference

#443 podvm: disable cloud-init unsafe modules for CoCo
  config/peerpods/podvm/lib.sh
Labels: lgtm
