Repository openshift/sandboxed-containers-operator, pull requests merged in 2024-03, with the labels that each got.

#376 credentials-controller: fetch credentials using cloud-credentials-operator
  PROJECT
  api/v1/kataconfig_webhook.go
  config/peerpods/credentials-requests/credentials_request_aws.yaml
  config/peerpods/credentials-requests/credentials_request_azure.yaml
  controllers/credentials_controller.go
  controllers/image_generator.go
  controllers/openshift_controller.go
  controllers/suite_test.go
  controllers/utils.go
  go.mod
  go.sum
  main.go
Labels: lgtm

#379 Bump version to 1.7.0
  Makefile
  config/manager/kustomization.yaml
  config/manifests/bases/sandboxed-containers-operator.clusterserviceversion.yaml
  config/samples/deploy.yaml
  hack/aws-image-job.yaml
  hack/azure-image-job.yaml
Labels: needs-ok-to-test

#383 Update peerpod controllers to v0.8.0-alpha.1
  go.mod
  go.sum
Labels: lgtm, ok-to-test
