Repository openshift/sandboxed-containers-operator, pull requests merged in 2024-12, with the labels that each got.

#488 Update OWNERS
  OWNERS
Labels: do-not-merge/hold, lgtm

#487 KATA-3270: pod overhead for peer pods reduce actual worker capacity
  controllers/openshift_controller.go
Labels: lgtm, ok-to-test, jira/valid-reference

#491 Switch base image of OSC to rhel9
  Dockerfile
  Makefile
  docs/DEVELOPMENT.md
Labels: lgtm

#485 dependency updates: move machine-config to latest
  Makefile
  bundle/manifests/kataconfiguration.openshift.io_kataconfigs.yaml
  bundle/manifests/sandboxed-containers-operator.clusterserviceversion.yaml
  config/crd/bases/kataconfiguration.openshift.io_kataconfigs.yaml
  config/rbac/role.yaml
  controllers/cm_event_handler.go
  controllers/credentials_controller.go
  controllers/layered_image_handler.go
  controllers/openshift_controller.go
  controllers/suite_test.go
  controllers/utils.go
  go.mod
  go.sum
  main.go
Labels: lgtm

#492 Automatic extension name
  bundle/manifests/sandboxed-containers-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  controllers/openshift_controller.go
  docs/DEVELOPMENT.md
Labels: lgtm
