Repository openshift/sandboxed-containers-operator, pull requests merged in 2025-02, with the labels that each got.

#523 Add file-based catalog for 4.17
  .tekton/fbc-pipeline.yaml
  .tekton/osc-fbc-4-17-pull-request.yaml
  .tekton/osc-fbc-4-17-push.yaml
  fbc/4.17/Dockerfile
  fbc/4.17/catalog-template.json
  fbc/4.17/catalog/sandboxed-containers-operator/catalog.json
  fbc/README.md
Labels: lgtm

#501 Adding libvirt provider to helper interactive script for setting peer-pods-cm
  scripts/cm-helpers/README.md
  scripts/cm-helpers/pp-cm-helper.sh
Labels: ok-to-test

#514 docker build: Use digit tag for Dockerfile UBI image
  Dockerfile
Labels: lgtm, ok-to-test

#530 baremetal-coco: Use kata-cc as runtimeclass name
  scripts/install-helpers/baremetal-coco/install.sh
Labels: needs-ok-to-test, lgtm, ok-to-test

#531 Use version tag for the RHCOS layer image
  scripts/install-helpers/baremetal-coco/layeredimage-cm-snp.yaml
  scripts/install-helpers/baremetal-coco/layeredimage-cm-tdx.yaml
Labels: lgtm

#499 Create libvirt pool and volume on KVM host & libvirt config map update
  config/peerpods/peerpodscm.yaml
  config/peerpods/peerpodssecret.yaml
  config/peerpods/podvm/README.md
  config/peerpods/podvm/libvirt-podvm-image-handler.sh
  controllers/image_generator.go
Labels: ok-to-test

#543 Misc fixes requires for the bootc PR
  config/peerpods/podvm/aws-podvm-image-handler.sh
  config/peerpods/podvm/azure-podvm-image-handler.sh
  config/peerpods/podvm/lib.sh
  config/peerpods/podvm/libvirt-podvm-image-handler.sh
  config/peerpods/podvm/podvm-handling.md
Labels: lgtm

#515 Snapshot deletion validation during KataConfig removal
  config/peerpods/podvm/aws-podvm-image-handler.sh
Labels: lgtm, ok-to-test

#533 Migrate PeerPodConfig Limit
  controllers/migrate.go
  controllers/openshift_controller.go
Labels: lgtm
