Repository openshift/sandboxed-containers-operator, pull requests merged in 2025-09, with the labels that each got.

#1041 Ibmcloud: initial support for release
  config/peerpods/podvm/Dockerfile.podvm-builder
  config/peerpods/podvm/ibmcloud-podvm-image-cm.yaml
  config/peerpods/podvm/ibmcloud-podvm-image-handler.sh
  config/peerpods/podvm/osc-podvm-create-job.yaml
  config/peerpods/podvm/osc-podvm-delete-job.yaml
  config/peerpods/podvm/podvm-builder.sh
  controllers/image_generator.go
  controllers/openshift_controller.go
Labels: lgtm, ok-to-test

#1042 chore(KONFLUX-6210): fix and set name and cpe label for osc-must-gather
  must-gather/Dockerfile
Labels: lgtm

#1043 chore(KONFLUX-6210): fix and set name and cpe label for osc-operator
  Dockerfile
Labels: lgtm

#1052 [1.10] Cherry picks for labels
  Dockerfile
  bundle.Dockerfile
  config/peerpods/podvm/Dockerfile.podvm-builder
  must-gather/Dockerfile
Labels: lgtm

#825 Daemonset deployment mode
  controllers/daemonset_reconcile.go
  controllers/deployment_mode_handler.go
  controllers/fg_handler.go
  controllers/openshift_controller.go
  controllers/utils.go
  go.mod
  go.sum
  scripts/kata-install/50-kata-remote
  scripts/kata-install/Dockerfile
  scripts/kata-install/configuration-remote.toml
  scripts/kata-install/lib.sh
  scripts/kata-install/osc-configs-script.sh
  scripts/kata-install/osc-kata-install.sh
  scripts/kata-install/osc-log-level.sh
Labels: ok-to-test

#1067 [1.10] Daemonset deployment mode
  controllers/daemonset_reconcile.go
  controllers/deployment_mode_handler.go
  controllers/fg_handler.go
  controllers/openshift_controller.go
  controllers/utils.go
  go.mod
  go.sum
  scripts/kata-install/50-kata-remote
  scripts/kata-install/Dockerfile
  scripts/kata-install/configuration-remote.toml
  scripts/kata-install/lib.sh
  scripts/kata-install/osc-configs-script.sh
  scripts/kata-install/osc-kata-install.sh
  scripts/kata-install/osc-log-level.sh
Labels: lgtm, ok-to-test

#1072 Add karg nohibernate to tdx host
  scripts/install-helpers/baremetal-coco/layeredimage-cm-tdx.yaml
Labels: needs-ok-to-test, ok-to-test

#1069 Refactor peerpods
  controllers/daemonset_reconcile.go
  controllers/openshift_controller.go
  controllers/peerpods.go
Labels: do-not-merge/hold, lgtm

#1082 Bump to 1.11.0
  Dockerfile
  Makefile
  bundle.Dockerfile
  bundle/manifests/sandboxed-containers-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/sandboxed-containers-operator.clusterserviceversion.yaml
  config/metrics/kustomization.yaml
  config/peerpods/podvm/Dockerfile.podvm-builder
  config/peerpods/podvm/bootc/Containerfile.rhel
  config/peerpods/podvm/osc-podvm-create-job.yaml
  config/peerpods/podvm/osc-podvm-delete-job.yaml
  config/peerpods/podvm/osc-podvm-gallery-delete-job.yaml
  config/samples/deploy.yaml
  docs/DEVELOPMENT.md
  must-gather/Dockerfile
  scripts/bump-osc-version.sh
Labels: lgtm
