Repository openshift/sandboxed-containers-operator, pull requests merged in 2025-06, with the labels that each got.

#665 baremetal-coco: bump intel device plugin operator to 0.32.1 release
  scripts/install-helpers/baremetal-coco/install.sh
  scripts/install-helpers/baremetal-coco/intel-dpo/install_operator.yaml
  scripts/install-helpers/baremetal-coco/intel-dpo/sgx_device_plugin.yaml
Labels: lgtm, ok-to-test

#652 Minor fixes
  .dockerignore
  config/peerpods/podvm/.dockerignore
  config/peerpods/podvm/aws-podvm-image-handler.sh
  config/peerpods/podvm/azure-podvm-image-handler.sh
  config/peerpods/podvm/bootc/.dockerignore
  config/peerpods/podvm/gcp-podvm-image-handler.sh
  config/peerpods/podvm/lib.sh
Labels: lgtm

#634 podvm: fix umoci checkout on s390x
  config/peerpods/podvm/libvirt-podvm-image-handler.sh
Labels: ok-to-test

#660 gcp: fixes image deletion
  config/peerpods/podvm/osc-podvm-delete-job.yaml
  controllers/image_generator.go
Labels: lgtm

#731 osc-operator: build with CGO_ENABLED=1 to comply with FIPS checks
  Makefile
Labels: lgtm

#746 make-test: install required dependencies
  tests/make-test.yaml
Labels: lgtm
