Repository openshift/sandboxed-containers-operator, pull requests merged in 2025-01, with the labels that each got.

#494 baremetal-coco: Add the namespace to the default kbs address
  scripts/install-helpers/baremetal-coco/install.sh
Labels: needs-ok-to-test, lgtm

#493 baremetal-coco: tdx: Add DCAP deployment
  scripts/install-helpers/baremetal-coco/install.sh
  scripts/install-helpers/baremetal-coco/intel-dcap/ns.yaml
  scripts/install-helpers/baremetal-coco/intel-dcap/pccs.yaml.in
  scripts/install-helpers/baremetal-coco/intel-dcap/qgs.yaml
  scripts/install-helpers/baremetal-coco/intel-dcap/registration-ds.yaml.in
Labels: needs-ok-to-test, lgtm, ok-to-test

#496 Bump to 1.9.0
  Makefile
  bundle/manifests/sandboxed-containers-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manifests/bases/sandboxed-containers-operator.clusterserviceversion.yaml
  config/metrics/kustomization.yaml
  config/peerpods/podvm/osc-podvm-create-job.yaml
  config/peerpods/podvm/osc-podvm-delete-job.yaml
  config/peerpods/podvm/osc-podvm-gallery-delete-job.yaml
  config/samples/deploy.yaml
  docs/DEVELOPMENT.md
  scripts/install-helpers/baremetal-coco/subs-ga.yaml
  scripts/install-helpers/baremetal-coco/subs-upstream.yaml
Labels: lgtm

#497 KATA-3493: toml file should include image annotations
  config/peerpods/local/configuration-remote.toml
  config/peerpods/mc-40-kata-remote-config.yaml
Labels: ok-to-test, jira/valid-reference

#502 baremetal-coco: Remove leftover instruction from the script
  scripts/install-helpers/baremetal-coco/install.sh
Labels: needs-ok-to-test, lgtm, ok-to-test

#508 docker build: make the build as user root
  Dockerfile
Labels: lgtm

#518 Add policy file for coco
  config/peerpods/podvm/agent-policy/coco-policy.rego
Labels: lgtm
